### ISSUE TITLE
Problemes commandes Plugin liveboxtv

### ISSUE THREAD

**Issue by hazenote** [Erim32/fr_liveboxtv#3]
Il y avais un soucis sur le plugin quand on essayer de faire une commande 

le plugin s'installer au mauvais endroit voila comment resoudre 

-cd /home/pi/jarvis/plugins/fr_liveboxtv/
-mkdir fr
-cp commands /home/pi/jarvis/plugins/fr_liveboxtv/fr/
A modifier
cette soluce n'est pas de moi mais je remercie  @tchoul 

Pour que le plugin soit optimal referez vous a l'autre modification dans l'onglet issue il vous faudra changer l'url pour que le plugin marche

**Comment by wikijm** [comment]
Je viens de créer le pull request https://github.com/Erim32/fr_liveboxtv/pull/4 pour corriger cela.

**Comment by hazenote** [comment]
super merci

**Comment by hazenote** [comment]
Une mise a jour a tout reparé !  Si quelqu'un veut les commandes qui reagissent a 'live box' je peux le donner j'ai modifier chaque ligne !

**Comment by Erim32** [comment]
Merci, les résultats sont ils meilleurs que avec l'ancien mot? 
Quel mot est le mieux reconnu lorsque l'on dit "Livebox" ? 
Je  mettrais à jour en fonction des retours.

**Comment by XxaayadixX** [comment]
@hazenote  j'ai le meme probleme, comment tu la resolu ?

**Comment by Erim32** [comment]
Normalement la mise à jour que j'ai faite devrait corriger le problème.  Peux-tu expliciter ta situation.

**Comment by XxaayadixX** [comment]
Le problème c'est que les commande sont très difficilement detectable,
quand elle le sont, j'ai l'impression de tomber dans une boucle infinie.
ps: pour l'ip de la livebox, si je donne celle en local ca devrais marcher ?
